from django.core.management.base import BaseCommand
from products.models import Banner, Blog, ServicePage

class Command(BaseCommand):
    help = "Seed HOOVALE service pages and practical wall-clock guides."

    def handle(self, *args, **kwargs):
        # Homepage carousel uses finished 3:2 artwork. Keep the database
        # records, but clear uploaded-image overrides so the repository artwork
        # is the single source of truth on Render and other ephemeral hosts.
        banner_specs = [
            ("wedding", "Wedding Gifts", "/static/images/banners/wedding-desktop.svg", 1),
            ("corporate", "Corporate Gifts", "/static/images/banners/corporate-desktop.svg", 2),
        ]
        for keyword, title, artwork, order in banner_specs:
            banner = (
                Banner.objects.filter(slug__icontains=keyword).order_by("order", "id").first()
                or Banner.objects.filter(title__icontains=keyword).order_by("order", "id").first()
            )
            if banner is None:
                banner = Banner(title=title, slug=title.lower().replace(" ", "-"), order=order)
            banner.title = title
            banner.desktop_image = ""
            banner.mobile_image = ""
            banner.image = ""
            banner.fallback_desktop = artwork
            banner.fallback_mobile = artwork
            banner.heading = ""
            banner.subheading = ""
            banner.cta_text = ""
            banner.overlay_opacity = 0
            banner.is_active = True
            banner.order = order
            banner.save()

        services = [
            ("Bulk Wall Clock Supply","fas fa-boxes-stacked","Bulk Wall Clock Supply for Retailers, Dealers & Businesses","Bulk supply for retailers, distributors, institutions and business buyers. Share quantity, preferred designs and delivery city for product and pricing guidance.","Bulk wall clock supply from Jaipur for retail and B2B requirements. HOOVALE helps buyers compare designs, quantities, branding options and delivery plans.","Share quantity and delivery city. Choose size, material and style. Review suitable products and pricing. Confirm packing, branding and dispatch details.","Product selection support; quantity-based pricing discussions; retail and B2B supply; branding discussions; delivery coordination.","Bulk Wall Clock Supply for Businesses | HOOVALE","Bulk wall clock supply from Jaipur for retailers, distributors, offices and business buyers. Discuss quantity, designs and delivery.","bulk wall clock supplier, wholesale wall clocks Jaipur, wall clock bulk order India",1),
            ("Custom Logo Printing","fas fa-pen-ruler","Custom Logo Wall Clocks for Brands & Corporate Gifting","Branded wall clocks for corporate gifting, dealer meets, promotional campaigns and branded spaces.","A useful branded wall clock should keep the dial readable while giving the logo a clear place. HOOVALE helps buyers discuss logo placement, artwork, clock size and quantity before production.","Share your logo and quantity. Select a clock format. Review branding layout. Confirm artwork, packing and delivery. Proceed with production.","Clear branding; useful corporate gifting; promotional visibility; artwork review; quantity planning.","Custom Logo Wall Clocks & Corporate Gifting | HOOVALE","Custom logo wall clocks for corporate gifts, dealer meets and promotions. Discuss artwork, clock size and quantity with HOOVALE Jaipur.","custom logo wall clock, corporate gifting clocks, branded wall clock India",2),
            ("OEM Manufacturing","fas fa-industry","OEM Wall Clock Manufacturing for Private Labels","Discuss product specifications, branding, quantities and packaging for private-label or OEM requirements.","OEM projects need clear specifications, quantities, branding, packaging and delivery planning. HOOVALE provides a starting point for businesses with defined custom or private-label wall clock requirements.","Share the product brief and expected volume. Review suitable formats. Discuss branding and packaging. Finalise artwork and production details. Schedule dispatch.","Specification-led discussion; private-label conversations; quantity planning; packaging considerations; order coordination.","OEM Wall Clock Manufacturing & Private Label | HOOVALE","Discuss OEM and private-label wall clock manufacturing with HOOVALE in Jaipur. Share specifications, quantity and branding requirements.","OEM wall clock manufacturer, private label wall clocks, custom wall clock manufacturing Jaipur",3),
            ("Corporate Gifting","fas fa-gift","Corporate Gifting Wall Clocks for Employees, Clients & Partners","Wall clocks for employee gifts, client appreciation, dealer programmes, events and business milestones.","Corporate gifts work best when they are useful after the event. Wall clocks can suit employee recognition, client appreciation, dealer programmes and business milestones.","Start with the occasion and quantity. Select a clock size and style. Share branding requirements. Confirm artwork, packing and delivery.","Useful long-term gift; suitable for different budgets; branding discussions; practical for employee and client programmes.","Corporate Gifting Wall Clocks for Businesses | HOOVALE","Choose wall clocks for corporate gifting, employee recognition, client gifts and dealer programmes. Discuss branding and bulk quantities.","corporate gifting wall clocks, employee gift clocks, client gifting India",4),
            ("Promotional Clocks","fas fa-bullhorn","Promotional Wall Clocks for Advertising & Brand Campaigns","Promotional wall clocks for dealer campaigns, events, customer programmes and branded giveaways.","Promotional wall clocks can keep a brand visible in a physical space. HOOVALE helps buyers discuss product format, branding area, quantity and delivery for campaigns.","Define the audience and quantity. Select the clock format. Share artwork. Review the layout. Confirm order and delivery.","Longer product life; visible brand placement; dealer and event use; scalable bulk requirements.","Promotional Wall Clocks for Brand Campaigns | HOOVALE","Promotional wall clocks for advertising, dealer campaigns, events and business giveaways. Discuss branding and bulk quantities.","promotional wall clocks, advertising clocks, branded promotional clocks India",5),
        ]
        for name,icon,h1,hero,short,process,benefits,mt,md,mk,order in services:
            ServicePage.objects.update_or_create(name=name, defaults=dict(icon_class=icon,h1_heading=h1,hero_subheading=hero,short_description=short,full_description=short+" "+hero,process_content=process,benefits_content=benefits,meta_title=mt,meta_description=md,meta_keywords=mk,is_published=True,display_order=order))

        posts = [
            ("How to Choose the Right Wall Clock for Your Home","Buying Guide","how to choose wall clock, wall clock for home, wall clock size guide","Learn how to choose a wall clock by room, size, readability, material, colour and placement.","""<p>Choosing a wall clock is mostly about proportion and readability. Start with the wall area, viewing distance and furniture around it rather than choosing a design first.</p><h2>Start with the wall</h2><p>A compact bedroom or study usually needs a lighter visual presence, while a living room or large wall can take a stronger clock. Leave breathing room around the dial.</p><h2>Choose a readable dial</h2><p>For offices, kitchens and common areas, clear markers and hands matter more than decoration. Check contrast and viewing distance before deciding.</p><h2>Match the material</h2><p>Wood-style finishes can add warmth, plastic can be practical for everyday or promotional use, and metal finishes can suit modern spaces.</p><h2>Quick checklist</h2><p>Measure the wall, estimate viewing distance, choose a readable dial and confirm the clock size before buying.</p>"""),
            ("Wall Clock Sizes Explained: 12, 18, 24 Inches and Beyond","Buying Guide","wall clock sizes, 12 inch wall clock, 18 inch wall clock, 24 inch wall clock","Compare common wall clock sizes and where they work best in homes, offices and commercial spaces.","""<p>Wall clock size should be judged against the whole wall. A 12-inch clock can work in a compact room but disappear on a large reception wall.</p><h2>12 inch</h2><p>Useful for bedrooms, studies, compact offices and smaller retail areas.</p><h2>18 inch</h2><p>A balanced choice for many living rooms, offices, classrooms and medium-sized reception areas.</p><h2>24 inch and larger</h2><p>Useful where people stand farther away or the wall has a lot of open space.</p><h2>Simple test</h2><p>Stand at the normal viewing position. If the markers are hard to read, consider moving up a size.</p>"""),
            ("Custom Logo Wall Clocks: Bulk Order Checklist","Custom Branding","custom logo wall clocks, branded clocks bulk order, corporate logo wall clock","Check logo artwork, placement, readability, quantity, packing and delivery before approving a branded clock order.","""<p>A branded wall clock should remain readable first. The safest approach is to approve the branding layout before production.</p><h2>Prepare clean artwork</h2><p>Use the best logo file available and check whether fine lines or small text will remain readable at the selected size.</p><h2>Choose the branding area</h2><p>Keep the logo clear without filling every part of the dial. A restrained layout usually looks more professional.</p><h2>Confirm quantity and delivery</h2><p>Share volume and destination early. Discuss packing and the required date before final approval.</p>"""),
            ("Promotional Wall Clocks for Advertising: When They Make Sense","Promotional Products","promotional wall clock, advertising wall clock, branded promotional products","Practical ideas for dealer campaigns, events, local advertising and customer giveaways.","""<p>A promotional product has to earn its place in the customer's space. A wall clock can be useful when a campaign needs a practical item that stays visible.</p><h2>Good use cases</h2><p>Consider promotional clocks for dealer networks, trade events, local campaigns, showroom branding and customer programmes.</p><h2>Keep branding useful</h2><p>Keep the logo clear and the clock readable. Avoid filling the dial with too much campaign copy.</p><h2>Plan quantities</h2><p>List campaign locations or recipients before deciding quantity, then discuss packing and delivery timing.</p>"""),
            ("Wholesale Wall Clocks: A Practical Buying Checklist for Retailers","Wholesale","wholesale wall clocks, wall clock wholesale supplier, buy wall clocks in bulk","A retailer checklist covering product mix, MOQ, pricing, packaging, repeat availability and delivery.","""<p>Wholesale buying is not only about the lowest piece price. Retailers also need a useful product mix, sensible packing and repeat supply.</p><h2>Build a product mix</h2><p>Start with styles and sizes that match your customers. Add decorative or promotional options where there is clear demand.</p><h2>Check MOQ and slabs</h2><p>Ask how quantity changes pricing and compare the expected landed cost rather than only the catalogue price.</p><h2>Plan repeat orders</h2><p>If a design sells well, ask whether it can be supplied again. Consistency can matter more than a one-time low price.</p>"""),
            ("Wooden vs Plastic vs Metal Wall Clocks","Materials","wooden vs plastic wall clock, metal wall clock, wall clock materials","Compare wooden, plastic and metal wall clocks by appearance, practical use, budget and typical buying situations.","""<p>No single material is right for every wall clock. The better choice depends on the room, design language, budget and order purpose.</p><h2>Wooden</h2><p>Wood-style finishes often suit warm interiors, cafés, offices and gifting requirements.</p><h2>Plastic</h2><p>Plastic designs can be practical for everyday use and larger promotional requirements.</p><h2>Metal</h2><p>Metal finishes can create a structured contemporary look for offices and modern interiors.</p><h2>Choose by use</h2><p>Consider installation location, quantity, viewing distance and branding before selecting material.</p>"""),
            ("Custom Photo Printed Wall Clocks: Gift Ideas","Custom Clocks","photo printed wall clock, personalised wall clock, custom photo clock","Ideas for photo clocks for anniversaries, weddings, birthdays, housewarming and personalised décor.","""<p>A photo printed wall clock combines a memory with a useful object. The best results usually come from a clear image, simple layout and enough space for the hands and markers.</p><h2>Choose the photo carefully</h2><p>Use an image with good lighting and enough resolution for the selected size.</p><h2>Protect the clock face</h2><p>Do not place important faces or details under the hands or markers. A beautiful image still needs to work as a clock.</p><h2>Good occasions</h2><p>Photo clocks can suit anniversaries, weddings, birthdays and housewarming gifts.</p>"""),
            ("How to Choose Wall Clocks for Offices and Institutions","Business & Office","office wall clocks, institutional wall clocks, reception wall clock","Choose office and institutional clocks by readability, size, placement, style and quantity.","""<p>In an office or institution, people should be able to read the time quickly from the normal viewing distance.</p><h2>Prioritise readability</h2><p>Choose clear markers and hands with good contrast. Reception and common areas may need a larger dial.</p><h2>Keep the style professional</h2><p>Clean layouts and neutral finishes work across offices, clinics, schools and reception areas.</p><h2>Plan multiple locations</h2><p>Create a location list before a larger order so size and style remain consistent.</p>"""),
            ("Wall Clocks for Wedding and Festive Gifting","Gifting","wedding gifting wall clock, festive wall clock gift, personalised clock gift","Simple advice on choosing wall clocks for weddings, housewarming, festive gifts and family occasions.","""<p>A good gifting clock should feel appropriate for the occasion while still fitting naturally into the recipient's home.</p><h2>Modern homes</h2><p>Clean dials, neutral finishes and simple frames are easy to match with existing décor.</p><h2>Traditional gifting</h2><p>Wood-style finishes and warmer colours can suit classic interiors.</p><h2>Personalisation</h2><p>Choose an image or message that will remain meaningful. Keep the clock face readable.</p><h2>Group gifting</h2><p>For employee or family gifts, consider a consistent design and discuss quantity pricing.</p>"""),
            ("Buying Wall Clocks Directly from a Jaipur Manufacturer: B2B Guide","Jaipur & Manufacturing","wall clock manufacturer Jaipur, wall clock supplier Jaipur, buy wall clocks Jaipur","Questions B2B buyers should ask about product range, quantity, branding, packing, documentation and delivery.","""<p>For B2B buyers, the right questions save time before an order is confirmed. Start with product fit, then discuss quantity, branding and delivery.</p><h2>Ask about the range</h2><p>Request sizes, materials and designs suitable for your use case. For promotional orders, explain the campaign rather than asking only for a generic catalogue.</p><h2>Confirm MOQ</h2><p>Minimum quantities and pricing slabs can change the economics of a project, so share expected volume early.</p><h2>Discuss artwork</h2><p>Ask where the logo can be placed, what artwork format is required and how the final layout will be approved.</p><h2>Clarify delivery</h2><p>Give the destination and required date. Discuss packing, dispatch timing and procurement documentation.</p>"""),
        ]
        for title,category,keywords,desc,html in posts:
            Blog.objects.update_or_create(title=title, defaults=dict(category=category,description=desc,content_html=html,meta_title=title[:70],meta_description=desc[:155],meta_keywords=keywords,is_published=True))
        self.stdout.write(self.style.SUCCESS(f"Seeded {len(services)} service pages and {len(posts)} blog guides."))