# Generated by Django 6.0.3 on 2026-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_moq_product_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(default='Wall Clocks', max_length=100)),
                ('featured_image', models.ImageField(upload_to='blog/%Y/%m/')),
                ('description', models.TextField(help_text='SEO optimized content')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='products_bl_created_e48fa9_idx')],
            },
        ),
    ]
