# Generated by Django 6.0.3 on 2026-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_citypage_faq_industrypage_servicepage_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(blank=True, default='default/blog-default.jpg', null=True, upload_to='blog/%Y/%m/'),
        ),
    ]
