# Generated by Django 6.0.3 on 2026-06-05 02:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_blog_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTierTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Admin label, e.g. 'Standard 5-tier', 'Premium Clocks', 'Budget Range'", max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('tier1_min_qty', models.PositiveIntegerField(default=1, help_text='Minimum order quantity for Tier 1', validators=[django.core.validators.MinValueValidator(1)])),
                ('tier1_max_qty', models.PositiveIntegerField(default=49, help_text="Maximum qty for Tier 1 (use 99999 for 'no upper limit')")),
                ('tier1_label', models.CharField(default='Sample / Trial', help_text="Display label, e.g. 'Sample / Trial'", max_length=50)),
                ('tier1_discount_type', models.CharField(choices=[('percent', '% Off per piece'), ('flat', '₹ Off per piece')], default='percent', max_length=10)),
                ('tier1_discount_value', models.DecimalField(decimal_places=2, default=0, help_text='If type=percent: 0–100. If type=flat: rupees off per piece', max_digits=8)),
                ('tier1_badge', models.CharField(blank=True, help_text="Optional badge text, e.g. 'MRP', 'Trial Price'", max_length=30)),
                ('tier2_min_qty', models.PositiveIntegerField(default=50)),
                ('tier2_max_qty', models.PositiveIntegerField(default=99)),
                ('tier2_label', models.CharField(default='Small Order', max_length=50)),
                ('tier2_discount_type', models.CharField(choices=[('percent', '% Off per piece'), ('flat', '₹ Off per piece')], default='percent', max_length=10)),
                ('tier2_discount_value', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('tier2_badge', models.CharField(blank=True, default='5% OFF', max_length=30)),
                ('tier3_min_qty', models.PositiveIntegerField(default=100)),
                ('tier3_max_qty', models.PositiveIntegerField(default=249)),
                ('tier3_label', models.CharField(default='Standard Bulk', max_length=50)),
                ('tier3_discount_type', models.CharField(choices=[('percent', '% Off per piece'), ('flat', '₹ Off per piece')], default='percent', max_length=10)),
                ('tier3_discount_value', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('tier3_badge', models.CharField(blank=True, default='10% OFF', max_length=30)),
                ('tier4_min_qty', models.PositiveIntegerField(default=250)),
                ('tier4_max_qty', models.PositiveIntegerField(default=499)),
                ('tier4_label', models.CharField(default='Large Order', max_length=50)),
                ('tier4_discount_type', models.CharField(choices=[('percent', '% Off per piece'), ('flat', '₹ Off per piece')], default='percent', max_length=10)),
                ('tier4_discount_value', models.DecimalField(decimal_places=2, default=15, max_digits=8)),
                ('tier4_badge', models.CharField(blank=True, default='15% OFF', max_length=30)),
                ('tier5_min_qty', models.PositiveIntegerField(default=500)),
                ('tier5_max_qty', models.PositiveIntegerField(default=99999, help_text='Set 99999 for open-ended (500+)')),
                ('tier5_label', models.CharField(default='Wholesale / OEM', max_length=50)),
                ('tier5_discount_type', models.CharField(choices=[('percent', '% Off per piece'), ('flat', '₹ Off per piece')], default='percent', max_length=10)),
                ('tier5_discount_value', models.DecimalField(decimal_places=2, default=20, max_digits=8)),
                ('tier5_badge', models.CharField(blank=True, default='Best Price 🏆', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Tier Template',
                'verbose_name_plural': 'Pricing Tier Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='custom_pricing_tiers',
            field=models.JSONField(blank=True, help_text='Override tiers for this product only. Leave blank to use the template. Format: list of 5 dicts with keys: min_qty, max_qty, label, discount_type (percent/flat), discount_value, badge.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='use_custom_tiers',
            field=models.BooleanField(default=False, help_text='Tick to use the custom tiers JSON above instead of the template.'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_tier_template',
            field=models.ForeignKey(blank=True, help_text='Select a reusable pricing template. Leave blank to use site default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.pricingtiertemplate'),
        ),
    ]
